// The languages array defines each dictionary that can be selected via the language picker.
// Template for adding more entries:
// {
//   id: "xx",
//   label: "Language",
//   nativeLabel: "Native Name",
//   code: "XX",
//   flag: "🇽🇽",
//   csvUrl: "i18n/wingspan-dict-xx.csv",
//   translationIndex: 2,
// },

export const languages = [
  {
    id: "hr",
    label: "Croatian",
    nativeLabel: "Hrvatski",
    code: "HR",
    flag: "🇭🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 4,
  },
  {
    id: "en",
    label: "English/no translation",
    nativeLabel: "English/no translation",
    code: "EN",
    flag: "🇬🇧",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 1,
  },
  {
    id: "af",
    label: "Afrikaans",
    nativeLabel: "Afrikaans",
    code: "AF",
    flag: "🇿🇦",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 5,
  },
  {
    id: "ar",
    label: "Arabic",
    nativeLabel: "العربية",
    code: "SA",
    flag: "🇸🇦",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 6,
  },
  {
    id: "az",
    label: "Azerbaijani",
    nativeLabel: "Azərbaycanca",
    code: "AZ",
    flag: "🇦🇿",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 7,
  },
  {
    id: "bg",
    label: "Bulgarian",
    nativeLabel: "Български",
    code: "BG",
    flag: "🇧🇬",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 8,
  },
  {
    id: "bn",
    label: "Bengali",
    nativeLabel: "বাংলা",
    code: "BD",
    flag: "🇧🇩",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 9,
  },
  {
    id: "ca",
    label: "Catalan",
    nativeLabel: "Català",
    code: "ES-CT",
    flag: "🇪🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 10,
  },
  {
    id: "cs",
    label: "Czech",
    nativeLabel: "Čeština",
    code: "CZ",
    flag: "🇨🇿",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 11,
  },
  {
    id: "de",
    label: "German",
    nativeLabel: "Deutsch",
    code: "DE",
    flag: "🇩🇪",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 12,
  },
  {
    id: "dk",
    label: "Danish",
    nativeLabel: "Dansk",
    code: "DK",
    flag: "🇩🇰",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 13,
  },
  {
    id: "el",
    label: "Greek",
    nativeLabel: "Ελληνικά",
    code: "GR",
    flag: "🇬🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 14,
  },
  {
    id: "eo",
    label: "Esperanto",
    nativeLabel: "Esperanto",
    code: "EO",
    flag: "🏳️",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 15,
  },
  {
    id: "es",
    label: "Spanish",
    nativeLabel: "Español",
    code: "ES",
    flag: "🇪🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 16,
  },
  {
    id: "es_es",
    label: "Spanish (Spain)",
    nativeLabel: "Español (España)",
    code: "ES",
    flag: "🇪🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 17,
  },
  {
    id: "et",
    label: "Estonian",
    nativeLabel: "Eesti",
    code: "EE",
    flag: "🇪🇪",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 18,
  },
  {
    id: "eu",
    label: "Basque",
    nativeLabel: "Euskara",
    code: "ES-PV",
    flag: "🇪🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 19,
  },
  {
    id: "fi",
    label: "Finnish",
    nativeLabel: "Suomi",
    code: "FI",
    flag: "🇫🇮",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 20,
  },
  {
    id: "fr",
    label: "French",
    nativeLabel: "Français",
    code: "FR",
    flag: "🇫🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 21,
  },
  {
    id: "he",
    label: "Hebrew",
    nativeLabel: "עברית",
    code: "IL",
    flag: "🇮🇱",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 22,
  },
  {
    id: "hu",
    label: "Hungarian",
    nativeLabel: "Magyar",
    code: "HU",
    flag: "🇭🇺",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 23,
  },
  {
    id: "id",
    label: "Indonesian",
    nativeLabel: "Bahasa Indonesia",
    code: "ID",
    flag: "🇮🇩",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 24,
  },
  {
    id: "fa",
    label: "Persian",
    nativeLabel: "فارسی",
    code: "IR",
    flag: "🇮🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 25,
  },
  {
    id: "is",
    label: "Icelandic",
    nativeLabel: "Íslenska",
    code: "IS",
    flag: "🇮🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 26,
  },
  {
    id: "it",
    label: "Italian",
    nativeLabel: "Italiano",
    code: "IT",
    flag: "🇮🇹",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 27,
  },
  {
    id: "jp",
    label: "Japanese",
    nativeLabel: "日本語",
    code: "JP",
    flag: "🇯🇵",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 28,
  },
  {
    id: "jp_latn",
    label: "Japanese (Romaji)",
    nativeLabel: "Nihongo",
    code: "JP",
    flag: "🇯🇵",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 29,
  },
  {
    id: "ko",
    label: "Korean",
    nativeLabel: "한국어",
    code: "KR",
    flag: "🇰🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 30,
  },
  {
    id: "lt",
    label: "Lithuanian",
    nativeLabel: "Lietuvių",
    code: "LT",
    flag: "🇱🇹",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 31,
  },
  {
    id: "lv",
    label: "Latvian",
    nativeLabel: "Latviešu",
    code: "LV",
    flag: "🇱🇻",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 32,
  },
  {
    id: "ne",
    label: "Nepali",
    nativeLabel: "नेपाली",
    code: "NP",
    flag: "🇳🇵",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 33,
  },
  {
    id: "nl",
    label: "Dutch",
    nativeLabel: "Nederlands",
    code: "NL",
    flag: "🇳🇱",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 34,
  },
  {
    id: "nn",
    label: "Norwegian Nynorsk",
    nativeLabel: "Norsk nynorsk",
    code: "NO",
    flag: "🇳🇴",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 35,
  },
  {
    id: "no",
    label: "Norwegian",
    nativeLabel: "Norsk",
    code: "NO",
    flag: "🇳🇴",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 36,
  },
  {
    id: "pl",
    label: "Polish",
    nativeLabel: "Polski",
    code: "PL",
    flag: "🇵🇱",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 37,
  },
  {
    id: "pt",
    label: "Portuguese",
    nativeLabel: "Português",
    code: "PT",
    flag: "🇵🇹",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 38,
  },
  {
    id: "pt_br",
    label: "Portuguese (Brazil)",
    nativeLabel: "Português (Brasil)",
    code: "BR",
    flag: "🇧🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 39,
  },
  {
    id: "pt_pt",
    label: "Portuguese (Portugal)",
    nativeLabel: "Português (Portugal)",
    code: "PT",
    flag: "🇵🇹",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 40,
  },
  {
    id: "ro",
    label: "Romanian",
    nativeLabel: "Română",
    code: "RO",
    flag: "🇷🇴",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 41,
  },
  {
    id: "ru",
    label: "Russian",
    nativeLabel: "Русский",
    code: "RU",
    flag: "🇷🇺",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 42,
  },
  {
    id: "sk",
    label: "Slovak",
    nativeLabel: "Slovenčina",
    code: "SK",
    flag: "🇸🇰",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 43,
  },
  {
    id: "sl",
    label: "Slovenian",
    nativeLabel: "Slovenščina",
    code: "SI",
    flag: "🇸🇮",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 44,
  },
  {
    id: "sr",
    label: "Serbian",
    nativeLabel: "Српски",
    code: "RS",
    flag: "🇷🇸",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 45,
  },
  {
    id: "sv",
    label: "Swedish",
    nativeLabel: "Svenska",
    code: "SE",
    flag: "🇸🇪",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 46,
  },
  {
    id: "th",
    label: "Thai",
    nativeLabel: "ไทย",
    code: "TH",
    flag: "🇹🇭",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 47,
  },
  {
    id: "tr",
    label: "Turkish",
    nativeLabel: "Türkçe",
    code: "TR",
    flag: "🇹🇷",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 48,
  },
  {
    id: "uk",
    label: "Ukrainian",
    nativeLabel: "Українська",
    code: "UA",
    flag: "🇺🇦",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 49,
  },
  {
    id: "zh",
    label: "Chinese (Simplified)",
    nativeLabel: "简体中文",
    code: "CN",
    flag: "🇨🇳",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 50,
  },
  {
    id: "zh_tw",
    label: "Chinese (Traditional)",
    nativeLabel: "繁體中文",
    code: "TW",
    flag: "🇹🇼",
    csvUrl: "data/wingspan-dict.csv",
    translationIndex: 51,
  },
];